theme: jekyll-theme-minimal
title: Frames of success Diving into the minds of movie wizards
description: A template website for ADA Project
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Backup Home
    url: backup-home
  - title: Backup Example
    url: backup-example
