theme: jekyll-theme-minimal
title: "Frames of success: Diving into the minds of movie wizards"
description: A template website for ADA Project

show_downloads: False

author:  George # testing
twitter_username: elonmusk # testing
github_username: Arthurepfl123 # testing

markdown: kramdown # testing
kramdown:
    math_engine: katex # testing

navigation:
  - title: Home
    url: /
  - title: Idea 1
    url: section-1
  - title: Idea 2
    url: section-2
  - title: Idea 3
    url: section-3
  - title: Backup Home
    url: backup-home
  - title: Backup Example
    url: backup-example
