theme: jekyll-theme-midnight # jekyll-theme-minimal
title: "Frames of success: Diving into the minds of movie wizards"
description: A template website for ADA Project

short_title: "Frames of success"
show_downloads: False

# author: George Lucas # testing, "author" not implemented in layouts
# twitter_username: elonmusk # testing
github_username: epfl-ada/ada-2023-project-crunchychicken

favicon: 'assets/img/camera_with_flash.png'

markdown: kramdown # testing
kramdown:
    math_engine: katex # testing

exclude:
  - backup-home.md
  - backup-example.md

navigation:
  - title: Home
    url: /
  - title: Idea 1
    url: section-1
  - title: Idea 2
    url: section-2
  - title: Idea 3
    url: section-3
  - title: Backup Home
    url: backup-home
  - title: Backup Example
    url: backup-example
