# to launch locally run:
# (requires ruby installed then gem install bundler)
#   $ cd docs
#   $ bundle install
#   $ bundle exec jekyll serve

title: "Frames of Success: Diving into the minds of movie wizards"
short_title: "Frames of success"
author: Chang Chun-Tzu, Arthur Lamour, Clémence Mayaux, Sepehr Mousavi, Romain Rochepeau
description: >- # this means to ignore newlines until next field
  A data story about the choices of the most successful directors.
  This data story is a part of a project for ADA.
github_username: epfl-ada/ada-2023-project-crunchychicken


remote_theme: "jeffreytse/jekyll-theme-yat"
yat:
  date_format: "%b %d, %Y"

header_pages:
  - index.md
  - categories.md
  - about.md

favicon: "/assets/img/camera_with_flash.png"  # TODO: Change?
content_width: "920px"
header_transparent: true
night_mode: "manual"

coolblack: #090a0b
spacegrey: #353535
snowwhite: #ffffff
orangered: #ff5100
greatgold: #f2cb05
greenblue: #389092

theme_color: snowwhite
brand_color: orangered  # custom color: "#1a8e42"
selection:
  color: "#ff00ff"
  background_color: "yellow"

code_badge:
  enabled: "true"
  color: "#fff"
  background_color: "#ff4e00"
  text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# Default layout settings
defaults:
  home:
    heading: "Untitled"
    subheading: "..."
    banner: "..."

# Default banner settings
banner:
  video: null             # Video banner source
  loop: true              # Video loop
  volume: 0               # Video volume (100% is 1.0)
  start_at: 0             # Video start time
  image: null             # Image banner source
  opacity: 0.5            # Banner opacity (100% is 1.0)
  background: "#000"      # Banner background (Could be a image)
  height: "640px"         # Banner default height
  min_height: null        # Banner minimum height
  heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
  subheading_style: null  # Custom subheading style (e.g. color: gold)

# Excerpt settings
excerpt:
  default_image: /assets/images/default-image.jpeg  # Default image when the image style is not none
  image_style: z          # Image layout style (It's value could be none, left, right, top, z, z-reverse)
  image_width: 38.2%      # Image default width
  image_height: 160px     # Image default height
  text_size: 350          # Words default size

# Photo previewer settings (PhotoSwipe 5)
# the options please refer to: https://photoswipe.com/options/
photo_previewer:
 gallery: "section.main"
 children: "a.photo-swipe"
 bgOpacity: 0.8
 padding:
   top: 20
   bottom: 40
   left: 100
   right: 100

# Click to top settings
click_to_top:
  light:
    background_color: "white"
    color: "#454545"
  dark:
    background_color: "#34323d"
    color: "#bbb"

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-spaceship
